### ISSUE TITLE
Demo Result Question

### ISSUE THREAD

**Issue by Yedis** [vchoutas/torch-mesh-isect#10]
Hi , @vchoutas 

Thanks for your awesome work! I just met some questions about your demo script `batch_smpl_untangle.py`.

I changed your optimizer from SGD to Adam, and set lr to 0.001, which is a normal configuration. The reason I did this is to optimize faster, since I noticed your original SGD version change little poses even after a lot of optimization.

In most cases, the loss started around 0.00003, then reduced to 0.00001

My questions are as follows :
1. even when the loss is 0.00000, there are still obvious collision. Is it normal ?  
2. Why we can't remove all collision. Even 10000 steps later and the meshes change a lot, there are still collisions. But since there are only collision loss and a little reg_loss, the script should solve all collision. 

I guess they are the result of  imperfection loss from `Capturing Hands in Action using Discriminative Salient Points and Physics Simulation`, but I am not quite sure. 

Following is 10000 steps result.

![image](https://user-images.githubusercontent.com/31688580/62839130-6110b500-bcb8-11e9-92b7-c8e671139e4f.png)

**Comment by Yedis** [comment]
Another question,

You said `The module can be used also for inter-penetrations of different meshes - for this the easiest and naive approach (without additional bookkeeping) is to fuse all meshes in a single mesh and treat inter-penetrations as self-penetrations.`

I did some experiments according your suggestion, and found the same problem.

In this case, I didn't change optimizer and learning rate. The loss started around 0.00005, then reduced to 0.00003, after 10000 steps.

initial meshes:
![Selection_135](https://user-images.githubusercontent.com/31688580/62839656-54dc2600-bcbf-11e9-9a8a-e224fa4df3c3.png)

meshes after 10000 steps optimization:
![Selection_136](https://user-images.githubusercontent.com/31688580/62839665-750be500-bcbf-11e9-86f1-a3db8647b0f3.png)

plot them in one image, red meshes are new meshes:
![image](https://user-images.githubusercontent.com/31688580/62839672-9a005800-bcbf-11e9-9859-2a53b1f4cb85.png)

My questions: 
1. Why still collision exist even after 10000 steps optimization.
2. In above images, you can see hands of two people move to the same direction, which is obviously bad for optimizing collision between people. Do you know why? 

Thanks a lot !     : )

**Comment by vchoutas** [comment]
@Yedis In general, some collisions (e.g. armpit-upper arm) cannot be removed, since SMPL does not model contact-based deformation.
In your first example the poses look completely unnatural, so the inter-penetrations make sense. 
In the second example, which variables are you using for the optimization? Pose and shape(betas)? Did you also include body translation? This would be the easiest thing to change to resolve the collisions between the two individuals.

**Comment by maoyali** [comment]
How to solve inter-penetrations of different meshes, could you please give a detail description? Thanks in advance~
