### ISSUE TITLE
set the environment variable $CUDA_SAMPLES_INC to the path that contains the header helper_math.h

### ISSUE THREAD

**Issue by electronicliujiang** [vchoutas/torch-mesh-isect#14]
how to set the environment variable $CUDA_SAMPLES_INC to the path that contains the header helper_math.h?

**Comment by electronicliujiang** [comment]
#include "helper_math.h"
                         ^
compilation terminated.
error: command '/usr/local/cuda-10.0/bin/nvcc' failed with exit status 1

**Comment by nileshkulkarni** [comment]
Download samples from (here)[https://github.com/NVIDIA/cuda-samples], and set the export CUDA_SMAPLE_INC path accordingly. 
That solution worked for me.

**Comment by vchoutas** [comment]
I just updated the README with a link to the CUDA samples repo, thanks @nileshkulkarni .
