### ISSUE TITLE
Error inside sort: radix_sort: failed on 2nd step: invalid argument Cuda failure src/bvh_cuda_op.cu:863: 'an illegal memory access was encountered'

### ISSUE THREAD

**Issue by mikeburon** [vchoutas/torch-mesh-isect#2]
Having trouble with the sort ... help please :)

**Comment by vchoutas** [comment]
Can you please share the exact error? Also, could you share the mesh that you use and get this error, so that I can reproduce it in my machine?

**Comment by mikeburon** [comment]
@vchoutas first of all, let me thank you for your fast response!
 I am using your project within smpl-expressive so the mesh is not saved right now... 

the full error is the following :
Start building BVH
Start computing triangle bounding boxes
Finished computing triangle bounding_boxes
Compute Triangle Bounding boxes = 0.016384 (ms)
Finished Calculating scene Bounding Box
Scene bounding box reduction = 0.085152 (ms)
Start Morton Code calculation ...
nb of triangles:20908
Finished calculating Morton Codes ...
Morton code calculation = 0.016384 (ms)
Creating triangle ID sequence
Finished creating triangle ID sequence ...
Starting Morton Code sorting!
Error inside sort: radix_sort: failed on 2nd step: invalid argument
Cuda failure src/bvh_cuda_op.cu:863: 'an illegal memory access was encountered'

**Comment by vchoutas** [comment]
@mikeburon Can you share an image-keypoint pair where the error happens? Then I can try reproducing it and work from there.

**Comment by mikeburon** [comment]
> @mikeburon Can you share an image-keypoint pair where the error happens? Then I can try reproducing it and work from there.

I have replied with the necessary data on smpl-expressive but just incase here is the data again.

[D.zip](https://github.com/vchoutas/torch-mesh-isect/files/3336181/D.zip)

**Comment by torpor29** [comment]
Hello, I got this error before, you can try this https://github.com/vchoutas/smplify-x/issues/3#issuecomment-507010114

**Comment by mikeburon** [comment]
amazing thanks for all help ! WORKED!
