### ISSUE TITLE
“double_vec_ops.h”: No such file or directory

### ISSUE THREAD

**Issue by BaldrLector** [vchoutas/torch-mesh-isect#21]
Does anyone know how to fix this error? Thanks

**Comment by Elody-07** [comment]
> Does anyone know how to fix this error? Thanks

Hello~ I have met the same problem. Did you solve it ?

**Comment by monacv** [comment]
@Elody-07  and @BaldrLector  could you please guide how you solved this problem? I have the same exact error:

`double_vec_ops.h: No such file or directory`

**Comment by dumoulina** [comment]
If anyone has the same issue, I have changed the include relative path to the real path in `setup.py` l.59
```
bvh_include_dirs = torch.utils.cpp_extension.include_paths() + [
    'include',
    osp.expandvars('$CUDA_SAMPLES_INC')]
```
to
```
bvh_include_dirs = torch.utils.cpp_extension.include_paths() + [
    '/FULL/PATH/include',
    osp.expandvars('$CUDA_SAMPLES_INC')]
```
It might be an issue coming from a different compiler.
