### ISSUE TITLE
How can I save this problem?

### ISSUE THREAD

**Issue by LeoMyMe** [vchoutas/torch-mesh-isect#33]
C:\Users\Leo\anaconda3\envs\PMC2D\include\pyerrors.h(315): note: 参见“HAVE_SNPRINTF”的前一个定义
src/bvh.cpp(30): error C3861: “AT_CHECK”: 找不到标识符
error: command 'C:\\Program Files\\Microsoft VisualStudio\\2022\\Professional\\VC\\Tools\\MSVC\\14.35.32215\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2

**Comment by chen-hao-ran** [comment]
Hi! How did you solve it
