### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by Yedis** [vchoutas/torch-mesh-isect#4]
Hi, @vchoutas 
Thanks for your awesome work.

When I try to run your code, I get following error:

``
Number of triangles =  13776
Segmentation fault (core dumped)
``
Do you know what happened?

**Comment by LogWell** [comment]
Hello, how do you solve this problem?

**Comment by ltz17** [comment]
I have the same problem, do you solved it?
