### ISSUE TITLE
Can't install successfully on windows

### ISSUE THREAD

**Issue by conorcodes** [vchoutas/torch-mesh-isect#5]
I'm having trouble getting this to work on Windows.  I get these errors when running setup.py

`src/bvh_cuda_op.cu(945): error: "#" not expected here

src/bvh_cuda_op.cu(945): error: expected an expression

src/bvh_cuda_op.cu(945): error: "#" not expected here

src/bvh_cuda_op.cu(945): error: expected an expression

src/bvh_cuda_op.cu(945): error: "#" not expected here

src/bvh_cuda_op.cu(945): error: expected an expression

src/bvh_cuda_op.cu(945): error: "#" not expected here

src/bvh_cuda_op.cu(945): error: expected an expression

src/bvh_cuda_op.cu(945): error: "#" not expected here

src/bvh_cuda_op.cu(945): error: "#" not expected here

src/bvh_cuda_op.cu(945): error: expected an expression

src/bvh_cuda_op.cu(945): error: "#" not expected here

src/bvh_cuda_op.cu(945): error: "#" not expected here

src/bvh_cuda_op.cu(945): error: expected an expression

src/bvh_cuda_op.cu(945): error: "#" not expected here

src/bvh_cuda_op.cu(945): error: expected an expression

src/bvh_cuda_op.cu(945): error: "#" not expected here

src/bvh_cuda_op.cu(945): error: expected an expression

src/bvh_cuda_op.cu(945): error: "#" not expected here

src/bvh_cuda_op.cu(945): error: expected an expression

src/bvh_cuda_op.cu(945): error: "#" not expected here

src/bvh_cuda_op.cu(945): error: expected an expression

src/bvh_cuda_op.cu(945): error: "#" not expected here

src/bvh_cuda_op.cu(945): error: identifier "start" is undefined

src/bvh_cuda_op.cu(945): error: identifier "stop" is undefined

src/bvh_cuda_op.cu(945): error: "#" not expected here

src/bvh_cuda_op.cu(945): error: expected an expression

src/bvh_cuda_op.cu(945): error: "#" not expected here

src/bvh_cuda_op.cu(945): error: "#" not expected here

src/bvh_cuda_op.cu(945): error: expected an expression

src/bvh_cuda_op.cu(945): error: "#" not expected here

src/bvh_cuda_op.cu(945): error: "#" not expected here

src/bvh_cuda_op.cu(945): error: expected an expression

src/bvh_cuda_op.cu(945): error: "#" not expected here

src/bvh_cuda_op.cu(945): error: expected an expression

src/bvh_cuda_op.cu(945): error: "#" not expected here

src/bvh_cuda_op.cu(945): error: expected an expression

src/bvh_cuda_op.cu(945): error: "#" not expected here

src/bvh_cuda_op.cu(945): error: "#" not expected here

src/bvh_cuda_op.cu(945): error: expected an expression

src/bvh_cuda_op.cu(945): error: "#" not expected here

src/bvh_cuda_op.cu(945): error: "#" not expected here

src/bvh_cuda_op.cu(945): error: expected an expression

src/bvh_cuda_op.cu(945): error: "#" not expected here

src/bvh_cuda_op.cu(945): error: "#" not expected here

src/bvh_cuda_op.cu(945): error: "#" not expected here

src/bvh_cuda_op.cu(945): error: "#" not expected here

src/bvh_cuda_op.cu(945): error: "#" not expected here

src/bvh_cuda_op.cu(945): error: "#" not expected here

src/bvh_cuda_op.cu(945): error: "#" not expected here

src/bvh_cuda_op.cu(945): error: "#" not expected here

src/bvh_cuda_op.cu(945): error: "#" not expected here

src/bvh_cuda_op.cu(945): error: "#" not expected here

src/bvh_cuda_op.cu(945): error: "#" not expected here

src/bvh_cuda_op.cu(945): error: "#" not expected here

src/bvh_cuda_op.cu(945): error: "#" not expected here

src/bvh_cuda_op.cu(945): error: "#" not expected here

src/bvh_cuda_op.cu(945): error: "#" not expected here

src/bvh_cuda_op.cu(945): error: "#" not expected here

src/bvh_cuda_op.cu(945): error: "#" not expected here

src/bvh_cuda_op.cu(945): error: "#" not expected here

src/bvh_cuda_op.cu(945): error: "#" not expected here

src/bvh_cuda_op.cu(945): error: "#" not expected here

src/bvh_cuda_op.cu(945): error: "#" not expected here

src/bvh_cuda_op.cu(945): error: "#" not expected here

src/bvh_cuda_op.cu(945): error: "#" not expected here

src/bvh_cuda_op.cu(945): error: "#" not expected here

src/bvh_cuda_op.cu(945): error: expected a ";"

src/bvh_cuda_op.cu(945): warning: variable "triangles_ptr" was declared but never referenced

src/bvh_cuda_op.cu(945): error: "#" not expected here

src/bvh_cuda_op.cu(945): error: expected an expression

src/bvh_cuda_op.cu(945): error: "#" not expected here

src/bvh_cuda_op.cu(945): error: expected an expression

src/bvh_cuda_op.cu(945): error: "#" not expected here

src/bvh_cuda_op.cu(945): error: expected an expression

src/bvh_cuda_op.cu(945): error: "#" not expected here

src/bvh_cuda_op.cu(945): error: expected an expression

src/bvh_cuda_op.cu(945): error: "#" not expected here

src/bvh_cuda_op.cu(945): error: "#" not expected here

src/bvh_cuda_op.cu(945): error: expected an expression

src/bvh_cuda_op.cu(945): error: "#" not expected here

src/bvh_cuda_op.cu(945): error: "#" not expected here

src/bvh_cuda_op.cu(945): error: expected an expression

src/bvh_cuda_op.cu(945): error: "#" not expected here

src/bvh_cuda_op.cu(945): error: expected an expression

src/bvh_cuda_op.cu(945): error: "#" not expected here

src/bvh_cuda_op.cu(945): error: expected an expression

src/bvh_cuda_op.cu(945): error: "#" not expected here

src/bvh_cuda_op.cu(945): error: expected an expression

src/bvh_cuda_op.cu(945): error: "#" not expected here

src/bvh_cuda_op.cu(945): error: expected an expression

src/bvh_cuda_op.cu(945): error: "#" not expected here

src/bvh_cuda_op.cu(945): error: identifier "start" is undefined

src/bvh_cuda_op.cu(945): error: identifier "stop" is undefined

src/bvh_cuda_op.cu(945): error: "#" not expected here

src/bvh_cuda_op.cu(945): error: expected an expression

src/bvh_cuda_op.cu(945): error: "#" not expected here

src/bvh_cuda_op.cu(945): error: "#" not expected here

src/bvh_cuda_op.cu(945): error: expected an expression

src/bvh_cuda_op.cu(945): error: "#" not expected here

src/bvh_cuda_op.cu(945): error: "#" not expected here

Error limit reached.
100 errors detected in the compilation of "C:/Users/fitzgcon/AppData/Local/Temp/1/tmpxft_00001d58_00000000-10_bvh_cuda_op.cpp1.ii".
Compilation terminated.
error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v9.2\\bin\\nvcc.exe' failed with exit status 1`

**Comment by vchoutas** [comment]
@conorcodes Unfortunately I don't have access to a Windows machine and can't help you with the compilation right now.

**Comment by conorcodes** [comment]
I did manage to get it installed.  Removing all debugging if statements in `AT_DISPATCH_FLOATING_TYPES(`
solved it for me.

**Comment by zhaishengfu** [comment]
@conorcodes  Do you means DEBUG_PRINT? I have the same error and delete all DEBUG_PRINT but still have the problem

**Comment by zhaishengfu** [comment]
I met new problem:
error LNK2001: undefined external symbol "public: long * __cdecl at::Tensor::data<long>(void)const " (??$data@J@Tensor@at@@QEBAPEAJXZ)

**Comment by jjf695214184** [comment]
> I met new problem:
> error LNK2001: undefined external symbol "public: long * __cdecl at::Tensor::data(void)const " (??$data@J@Tensor@at@@QEBAPEAJXZ)

Have you solve it? I meet the same problem.

**Comment by conorcodes** [comment]
@zhaishengfu Here's my modified file that works on windows:

<script src="https://gist.github.com/conorcodes/612f3358f0c2569f26e07c5fd86345fe.js"></script>

**Comment by electronicliujiang** [comment]
how to run this code in win10?

**Comment by zhaishengfu** [comment]
thanks @conorcodes

**Comment by conorcodes** [comment]
hi @electronicliujiang check the gist I posted above.  That works for me on windows10

**Comment by schul016** [comment]
I updated bvh_cuda_op.cu using the git above @conorcodes.  I now get this error:

C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:c:\Python\lib\site-packages\torch\lib "/LIBPATH:C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\lib/x64" /LIBPATH:C:\cudnn\cuda\bin\lib/x64 /LIBPATH:c:\Python\libs /LIBPATH:c:\Python\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB\amd64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.10240.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x64" cudart.lib c10.lib c10_cuda.lib caffe2.lib torch.lib torch_python.lib caffe2_gpu.lib _C.lib /EXPORT:PyInit_bvh_cuda build\temp.win-amd64-3.7\Release\src/bvh.obj build\temp.win-amd64-3.7\Release\src/bvh_cuda_op.obj /OUT:build\lib.win-amd64-3.7\bvh_cuda.cp37-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.7\Release\src\bvh_cuda.cp37-win_amd64.lib
LINK : fatal error LNK1181: cannot open input file 'c10_cuda.lib'
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\link.exe' failed with exit status 1181

**Comment by BboyHanat** [comment]
> I met new problem:
> error LNK2001: undefined external symbol "public: long * __cdecl at::Tensor::data(void)const " (??$data@J@Tensor@at@@QEBAPEAJXZ)

Hey, I encountered the same error, may I know you solution to the problem?
