### ISSUE TITLE
error: command '/usr/local/cuda/bin/nvcc' failed with exit status 2

### ISSUE THREAD

**Issue by liwenssss** [vchoutas/torch-mesh-isect#8]
hi, @vchoutas 
When I install , I meet an error:
`2 errors detected in the compilation of "/tmp/tmpxft_00005eb9_00000000-7_bvh_cuda_op.cpp1.ii".
error: command '/usr/local/cuda/bin/nvcc' failed with exit status 2
`
I goole it but not find something help about status 2. Can you help me , I want to know why and solve it soon .Thx~!!!!

**Comment by vchoutas** [comment]
@liwenssss What version of CUDA are you using? Can you please provide a more detailed error message?

**Comment by liwenssss** [comment]
@vchoutas thx for replying.I just reslove by add some headers in some C++ file.I think it may be about the version of my g++. You can close it now. Sorry for I forget to say it.

**Comment by haoyz** [comment]
Hi, @liwenssss 
I also meet this error now. I google it and find that it can be solved by updating CUDA version to 9.2.
https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html
But it is a little difficult for me to change CUDA version. So I wonder what version of CUDA you are using and what headers you adding. If cuda 8.0, then I can also solved it by adding the headers without CUDA version update.

**Comment by liwenssss** [comment]
Hi, @haoyz ,
Sorry it was too long ago and I didn't remember it. You can read the error message and you can find it.
