### ISSUE TITLE
where is the the part segmentation file for the faces of the model?

### ISSUE THREAD

**Issue by li19960612** [vchoutas/torch-mesh-isect#9]
There is a parameter that specifies the body parts in batch_smpl_untangle.py, but I can't find this file. Can you tell me how I can get the file?

**Comment by li19960612** [comment]
There is a parameter that specifies the body parts in batch_smpl_untangle.py, but I can't find this file. Can you tell me how I can get the file?

**Comment by vchoutas** [comment]
@li19960612 You can find the file [here](https://owncloud.tuebingen.mpg.de/index.php/s/jHdgwkREzS43rjN). 
I will update the README as well.

**Comment by li19960612** [comment]
@vchoutas Thank you!

**Comment by li19960612** [comment]
And can you provide the way to add extra "ign_part_pairs" in class FilterFaces?

**Comment by vchoutas** [comment]
@li19960612 You can find an example for the `ign_part_pairs` in the [SMPLify-X config](https://github.com/vchoutas/smplify-x/blob/master/cfg_files/fit_smplx.yaml).

**Comment by li19960612** [comment]
@vchoutas Oh, It does work, thank you!
